### PR TITLE
SciPy 2017 talk proposal

### PR DESCRIPTION
**Pull request by ccordoba12**
@spyder-ide/core-developers and @spyder-ide/junior-developers, please take a look at the proposal and let me know what you think.

We only have until today to submit it, so I need a quick answer from you. I'm sorry to do this so last minute but I've been a bit sick for the last week and a half :-/

### CODE REVIEW

**Comment by andfoy** [comment]
Great! I think that the proposal resumes all our recent work and introduction of new plugins

**Comment by jitseniesen** [comment]
I wouldn't mind if you also plugged the older plugins in your talk :wink:

**Comment by ccordoba12** [comment]
I'm really sorry!! I only noticed that I could also talk about the plugins you maintain after I submitted the proposal :-/

But I'll talk about them for sure if our talk is accepted ;-)

**Comment by jitseniesen** [comment]
Don't worry about it

**Pull request merged**
